# Generated by Django 6.0.7 on 2026-07-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='delivery_state',
        ),
    ]
